# Continuum-Mechanics-MFEM flux-kernel framework.
# Out-of-tree build: every object, dependency file, the library
# $(BUILD_DIR)/lib$(LIBNAME).a, and the executables under $(BUILD_DIR)/apps
# and $(BUILD_DIR)/tests. Sources stay clean; `make clean` removes $(BUILD_DIR).
# Configuration discovery follows the myapps makefiles (MFEM config.mk).

LIBNAME ?= cmf
BUILD_DIR ?= build

MFEM_DIR ?= ../..
MFEM_BUILD_DIR ?= $(MFEM_DIR)
MFEM_INSTALL_DIR ?= ../../mfem

CONFIG_MK ?= $(or $(wildcard $(MFEM_BUILD_DIR)/config/config.mk),\
	$(wildcard $(MFEM_INSTALL_DIR)/share/mfem/config.mk),\
	$(wildcard $(HOME)/MFEM/mfem/config/config.mk),\
	$(wildcard $(HOME)/mfem/config/config.mk),\
	$(wildcard /opt/mfem/config/config.mk),\
	$(wildcard /usr/local/mfem/config/config.mk),\
	$(shell for d in .. ../.. ../../.. ../../../.. ../../../../..; do \
		if [ -f $$d/config/config.mk ]; then echo $$d/config/config.mk; exit 0; \
		elif [ -f $$d/share/mfem/config.mk ]; then echo $$d/share/mfem/config.mk; exit 0; fi; \
	done))

ifneq ($(wildcard $(CONFIG_MK)),)
MFEM_CONFIG_DIR := $(dir $(CONFIG_MK))
MFEM_ROOT_FROM_CONFIG := $(patsubst %config/,%,$(MFEM_CONFIG_DIR))
MFEM_ROOT_FROM_CONFIG := $(patsubst %share/mfem/,%,$(MFEM_ROOT_FROM_CONFIG))
ifneq ($(filter command line environment,$(origin MFEM_BUILD_DIR)),command line environment)
MFEM_BUILD_DIR := $(MFEM_ROOT_FROM_CONFIG)
export MFEM_BUILD_DIR
endif
ifneq ($(filter command line environment,$(origin MFEM_DIR)),command line environment)
MFEM_DIR := $(MFEM_ROOT_FROM_CONFIG)
export MFEM_DIR
endif
-include $(CONFIG_MK)
else
$(warning MFEM config.mk not found. Set MFEM_BUILD_DIR or MFEM_INSTALL_DIR to locate it.)
endif

MFEM_CXX ?= g++
MFEM_FLAGS ?= -O2 -std=c++17
MFEM_LIBS ?=
MFEM_MPIEXEC ?= mpirun

YAML_CXXFLAGS ?= $(shell pkg-config --cflags yaml-cpp 2>/dev/null)
YAML_LIBS ?= $(shell pkg-config --libs yaml-cpp 2>/dev/null)

WARNFLAGS ?= -Wall
# Materials live under src/kernels/materials and are included as materials/...
CPPFLAGS += -Isrc -Isrc/kernels
CXXFLAGS_ALL := $(MFEM_FLAGS) $(YAML_CXXFLAGS) $(WARNFLAGS) $(CPPFLAGS)
LINK_LIBS := $(MFEM_LIBS) $(YAML_LIBS) -lyaml-cpp

LIB := $(BUILD_DIR)/lib$(LIBNAME).a
LIB_SRC := $(sort $(wildcard src/*/*.cpp src/*/*/*.cpp))
LIB_OBJ := $(patsubst %.cpp,$(BUILD_DIR)/%.o,$(LIB_SRC))
APP_SRC := $(sort $(wildcard apps/*.cpp))
APPS := $(patsubst %.cpp,$(BUILD_DIR)/%,$(APP_SRC))
TEST_SRC := $(sort $(wildcard tests/*.cpp))
TESTS := $(patsubst %.cpp,$(BUILD_DIR)/%,$(TEST_SRC))
DEPS := $(LIB_OBJ:.o=.d) $(patsubst %.cpp,$(BUILD_DIR)/%.d,$(APP_SRC) $(TEST_SRC))

APP := $(BUILD_DIR)/apps/solid_mechanics
TEST_OUT := $(BUILD_DIR)/tests/out

.PHONY: all lib apps tests check homogeneous meshes test clean

all: lib apps tests

lib: $(LIB)
apps: $(APPS)
tests: $(TESTS)

$(LIB): $(LIB_OBJ)
	@mkdir -p $(dir $@)
	ar rcs $@ $^

$(APPS): $(BUILD_DIR)/apps/%: $(BUILD_DIR)/apps/%.o $(LIB)
	$(MFEM_CXX) $(MFEM_FLAGS) $< -o $@ $(LIB) $(LINK_LIBS)

$(TESTS): $(BUILD_DIR)/tests/%: $(BUILD_DIR)/tests/%.o $(LIB)
	$(MFEM_CXX) $(MFEM_FLAGS) $< -o $@ $(LIB) $(LINK_LIBS)

# Objects and their .d dependency fragments land beside each other in
# $(BUILD_DIR), mirroring the source tree.
$(BUILD_DIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(MFEM_CXX) $(CXXFLAGS_ALL) -MMD -MP -c $< -o $@

-include $(DEPS)

# Meshes of the example inputs, generated by Gmsh from apps/mesh/*.geo
# (physical groups -> attributes and names). The .msh files are kept in the
# tree so that running the inputs and tests does not need Gmsh.
GMSH ?= gmsh
MESH_DIR := apps/mesh
MESHES := $(MESH_DIR)/square.msh $(MESH_DIR)/cook.msh $(MESH_DIR)/cube.msh $(MESH_DIR)/beam.msh $(MESH_DIR)/annulus.msh \
	$(MESH_DIR)/cube10.msh $(MESH_DIR)/shear_cube.msh $(MESH_DIR)/column_buckling.msh $(MESH_DIR)/column_twist.msh \
	$(MESH_DIR)/cylinder_torsion.msh $(MESH_DIR)/plate_hole.msh $(MESH_DIR)/tube_quarter.msh \
	$(MESH_DIR)/sphere_octant.msh $(MESH_DIR)/footing.msh $(MESH_DIR)/inclusion.msh
meshes: $(MESHES)
$(MESH_DIR)/square.msh: $(MESH_DIR)/square.geo
	$(GMSH) -2 -format msh22 -setnumber n 4 -o $@ $< > /dev/null
$(MESH_DIR)/cook.msh: $(MESH_DIR)/cook.geo
	$(GMSH) -2 -format msh22 -setnumber n 4 -o $@ $< > /dev/null
$(MESH_DIR)/cube.msh: $(MESH_DIR)/box.geo
	$(GMSH) -3 -format msh22 -setnumber nx 2 -setnumber ny 2 -setnumber nz 2 -o $@ $< > /dev/null
$(MESH_DIR)/beam.msh: $(MESH_DIR)/box.geo
	$(GMSH) -3 -format msh22 -setnumber Lx 10 -setnumber nx 20 -setnumber ny 2 -setnumber nz 2 -o $@ $< > /dev/null
$(MESH_DIR)/annulus.msh: $(MESH_DIR)/annulus.geo
	$(GMSH) -2 -order 2 -format msh22 -o $@ $< > /dev/null
# Meshes of apps/input/anand_coupled_theories/finite_elasticity (the examples of Anand's book,
# FEniCSx codes at solidmechanicscoupledtheories.github.io, section 1).
$(MESH_DIR)/cube10.msh: $(MESH_DIR)/box.geo
	$(GMSH) -3 -format msh22 -setnumber Lx 10 -setnumber Ly 10 -setnumber Lz 10 -setnumber nx 4 -setnumber ny 4 -setnumber nz 4 -o $@ $< > /dev/null
$(MESH_DIR)/shear_cube.msh: $(MESH_DIR)/box.geo
	$(GMSH) -3 -format msh22 -setnumber nx 8 -setnumber ny 8 -setnumber nz 4 -o $@ $< > /dev/null
$(MESH_DIR)/column_buckling.msh: $(MESH_DIR)/box.geo $(MESH_DIR)/perturb_column.py
	$(GMSH) -3 -format msh22 -setnumber Lz 20 -setnumber nx 4 -setnumber ny 4 -setnumber nz 50 -o $@.straight $< > /dev/null
	python3 $(MESH_DIR)/perturb_column.py $@.straight $@ 20 0.005 && rm -f $@.straight
$(MESH_DIR)/column_twist.msh: $(MESH_DIR)/box.geo
	$(GMSH) -3 -format msh22 -setnumber Lz 3 -setnumber nx 8 -setnumber ny 8 -setnumber nz 32 -o $@ $< > /dev/null
$(MESH_DIR)/cylinder_torsion.msh: $(MESH_DIR)/cylinder_torsion.geo
	$(GMSH) -3 -order 2 -format msh22 -o $@ $< > /dev/null
$(MESH_DIR)/plate_hole.msh: $(MESH_DIR)/plate_hole.geo
	$(GMSH) -3 -order 2 -format msh22 -o $@ $< > /dev/null
$(MESH_DIR)/tube_quarter.msh: $(MESH_DIR)/tube_quarter.geo
	$(GMSH) -3 -order 2 -format msh22 -o $@ $< > /dev/null
$(MESH_DIR)/sphere_octant.msh: $(MESH_DIR)/sphere_octant.geo
	$(GMSH) -3 -order 2 -format msh22 -o $@ $< > /dev/null
$(MESH_DIR)/footing.msh: $(MESH_DIR)/footing.geo
	$(GMSH) -3 -format msh22 -o $@ $< > /dev/null
$(MESH_DIR)/inclusion.msh: $(MESH_DIR)/inclusion.geo
	$(GMSH) -3 -format msh22 -o $@ $< > /dev/null

# Fast gates (S1-S3 + mixed + homogeneous deformations + loading): serial unit and MMS tests.
CHECK_TESTS := $(addprefix $(BUILD_DIR)/tests/,test_base test_materials test_solid_mms test_mixed test_homogeneous test_loading)
check: $(CHECK_TESTS)
	@for t in $(CHECK_TESTS); do echo "== $$t"; ./$$t || exit 1; done

# The app on the homogeneous-deformation inputs (incompressible neo-Hookean),
# compared with the closed-form solutions (needs python3 with PyYAML).
homogeneous: $(APP)
	python3 apps/homogeneous_compare.py --app $(APP)

# Full gates (S4): fast gates, the YAML-driven app runs serial and np=4,
# np={2,4} consistency vs a serial reference, and the benchmarks with the
# frozen Cook's membrane regression values, serial and np=4. Run from the
# repository root: the inputs are referenced as apps/input/<set>/*.yaml.
test: check $(APP) $(BUILD_DIR)/tests/test_benchmarks $(BUILD_DIR)/tests/test_parallel
	$(APP) -i apps/input/finite_elasticity/cooks_membrane/cook.yaml
	$(MFEM_MPIEXEC) -np 4 $(APP) -i apps/input/finite_elasticity/cooks_membrane/cook.yaml
	$(APP) -i apps/input/finite_elasticity/cantilever3d.yaml
	mkdir -p $(TEST_OUT)
	$(BUILD_DIR)/tests/test_parallel --write $(TEST_OUT)/parallel_reference.txt
	$(MFEM_MPIEXEC) -np 2 $(BUILD_DIR)/tests/test_parallel --check $(TEST_OUT)/parallel_reference.txt
	$(MFEM_MPIEXEC) -np 4 $(BUILD_DIR)/tests/test_parallel --check $(TEST_OUT)/parallel_reference.txt
	$(APP) -i apps/input/finite_elasticity/cooks_membrane/cook_incompressible.yaml
	$(MFEM_MPIEXEC) -np 4 $(APP) -i apps/input/finite_elasticity/cooks_membrane/cook_incompressible.yaml
	python3 apps/homogeneous_compare.py --app $(APP)
	$(BUILD_DIR)/tests/test_mixed --full
	$(BUILD_DIR)/tests/test_benchmarks
	$(MFEM_MPIEXEC) -np 4 $(BUILD_DIR)/tests/test_benchmarks
	$(MFEM_MPIEXEC) -np 4 $(BUILD_DIR)/tests/test_loading
	$(BUILD_DIR)/tests/test_benchmarks --cook-ratio-gate

clean:
	rm -rf $(BUILD_DIR)
