// Auto-generated by text2code. Do not edit by hand.
// Regenerate with `text2code <pdeapp.txt>`.
//
// This header is consumed by `<exasim/model.hpp>`'s templated FEM
// internals. The struct below satisfies the Model contract; the
// inherited `ModelDefaults<GeneratedModel>` supplies zero-fill
// defaults for any optional method this PDE doesn't define.
#pragma once

#include <Kokkos_Core.hpp>
struct PdeModel : ModelDefaults<PdeModel> {
    static constexpr int nd     = 2;
    static constexpr int ncu    = 4;
    static constexpr int ncw    = 0;
    static constexpr int nco    = 2;
    static constexpr int nparam = 11;
    static constexpr int ntau   = 1;
    static constexpr int nsca   = 4;
    static constexpr int nvec   = 1;
    static constexpr int nten   = 0;
    static constexpr int nsurf  = 0;
    static constexpr int nvqoi  = 0;
    static constexpr int Nq = ncu * (1 + nd);

    static constexpr bool has_external_coupling = true;
    static constexpr int nfint  = 1;
    static constexpr int nfext  = 4;
    static constexpr int ncuext = 1;

    KOKKOS_INLINE_FUNCTION static
    void flux(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype uq6 = uq[6];
        const dstype uq7 = uq[7];
        const dstype uq8 = uq[8];
        const dstype uq9 = uq[9];
        const dstype uq10 = uq[10];
        const dstype uq11 = uq[11];
        const dstype v0 = v[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = -0.01 + uq0;
        const dstype x1 = x0*(0.5 + 0.318309886183791*Kokkos::atan(1000.0*x0));
        const dstype x2 = 0.000318309780080525 + x1;
        const dstype x3 = 0.5 + 318.309886183791*x2/(1 + 1000000.0*Kokkos::pow(x2, 2)) + 0.318309886183791*Kokkos::atan(1000.0*x2);
        const dstype x4 = v0*x3;
        const dstype x5 = 0.0103183097800805 + x1;
        const dstype x6 = Kokkos::pow(x5, -1);
        const dstype x7 = x3*uq8;
        const dstype x8 = x6*uq2;
        const dstype x9 = uq10 - x8*x7;
        const dstype x10 = x6*x9;
        const dstype x11 = x6*uq1;
        const dstype x12 = x3*uq4;
        const dstype x13 = uq5 - x12*x11;
        const dstype x14 = x6*x13;
        const dstype x15 = Kokkos::pow(uq2, 2);
        const dstype x16 = Kokkos::pow(x5, -2);
        const dstype x17 = Kokkos::pow(uq1, 2);
        const dstype x18 = 0.5*(x15*x16 + x17*x16);
        const dstype x19 = -1.0 + mu0;
        const dstype x20 = -0.001 + x19*(uq3 - x5*x18);
        const dstype x21 = x20*(0.5 + 0.318309886183791*Kokkos::atan(1000.0*x20));
        const dstype x22 = 0.00131830978008052 + x21;
        const dstype x23 = x6*x22;
        const dstype x24 = 1.0*mu0;
        const dstype x25 = (110.4 + mu9)*Kokkos::sqrt(Kokkos::pow(x22, 3)*Kokkos::pow(mu3, 6)*Kokkos::pow(mu0, 3)/Kokkos::pow(x5, 3))/(mu1*(110.4 + x24*x23*Kokkos::pow(mu3, 2)*mu9));
        const dstype x26 = 0.666666666666667*x25;
        const dstype x27 = (-x10 + 2*x14)*x26;
        const dstype x28 = uq6 - x8*x12;
        const dstype x29 = uq9 - x7*x11;
        const dstype x30 = 1.0*(x6*x28 + x6*x29)*x25;
        const dstype x31 = x30 + uq2*x11;
        const dstype x32 = x3*x22;
        const dstype x33 = uq2*x16;
        const dstype x34 = uq1*x16;
        const dstype x35 = 0.000318309780080518 + x21;
        const dstype x36 = x5*x19*(0.5 + 318.309886183791*x35/(1 + 1000000.0*Kokkos::pow(x35, 2)) + 0.318309886183791*Kokkos::atan(1000.0*x35));
        const dstype x37 = x24*x25*x16/(x19*mu2);
        const dstype x38 = x23 + x6*uq3;
        const dstype x39 = (2*x10 - x14)*x26;

        f[0] = uq1 + x4*uq4;
        f[1] = x22 + x27 + v0*uq5 + x6*x17;
        f[2] = x31 + v0*uq6;
        f[3] = uq1*x38 + v0*uq7 + x27*x11 + x37*(-uq4*x32 + x36*(uq7 - x12*x18 - (x33*x28 + x34*x13)*x5)) + x8*x30;
        f[4] = uq2 + x4*uq8;
        f[5] = x31 + v0*uq9;
        f[6] = x22 + x39 + v0*uq10 + x6*x15;
        f[7] = uq2*x38 + v0*uq11 + x30*x11 + x37*(-uq8*x32 + x36*(uq11 - x5*(x34*x29 + x9*x33) - x7*x18)) + x8*x39;
    }

    KOKKOS_INLINE_FUNCTION static
    void source(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 0;
        f[1] = 0;
        f[2] = 0;
        f[3] = 0;
    }

    KOKKOS_INLINE_FUNCTION static
    void tdfunc(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 1;
        f[1] = 1;
        f[2] = 1;
        f[3] = 1;
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_scalars(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];

        const dstype x0 = Kokkos::pow(uq0, -1);

        f[0] = uq0;
        f[1] = x0*uq1;
        f[2] = x0*uq2;
        f[3] = 0.4*(uq3 - 0.5*(x0*Kokkos::pow(uq1, 2) + x0*Kokkos::pow(uq2, 2)));
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_vectors(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];

        f[0] = uq1;
        f[1] = uq2;
    }

    KOKKOS_INLINE_FUNCTION static
    void initu(dstype f[], const dstype x[], const dstype uinf[], const dstype mu[]) {
        const dstype mu4 = mu[4];
        const dstype mu5 = mu[5];
        const dstype mu6 = mu[6];
        const dstype mu7 = mu[7];

        f[0] = mu4;
        f[1] = mu5;
        f[2] = mu6;
        f[3] = mu7;
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];
            const dstype mu4 = mu[4];
            const dstype mu5 = mu[5];
            const dstype mu6 = mu[6];
            const dstype mu7 = mu[7];

            f[0] = mu4 - uhat0;
            f[1] = mu5 - uhat1;
            f[2] = mu6 - uhat2;
            f[3] = mu7 - uhat3;
        }
        else if (ib == 2) {
            const dstype uq0 = uq[0];
            const dstype uq1 = uq[1];
            const dstype uq2 = uq[2];
            const dstype uq3 = uq[3];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];

            f[0] = -uhat0 + uq0;
            f[1] = -uhat1 + uq1;
            f[2] = -uhat2 + uq2;
            f[3] = -uhat3 + uq3;
        }
        else if (ib == 3) {
            const dstype uq0 = uq[0];
            const dstype uhat0 = uh[0];
            const dstype uhat1 = uh[1];
            const dstype uhat2 = uh[2];
            const dstype uhat3 = uh[3];
            const dstype mu8 = mu[8];
            const dstype mu9 = mu[9];
            const dstype mu10 = mu[10];

            f[0] = -uhat0 + uq0;
            f[1] = -uhat1;
            f[2] = -uhat2;
            f[3] = -uhat3 + mu8*mu10*uhat0/mu9;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void flux_jac_uq(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype uq6 = uq[6];
        const dstype uq7 = uq[7];
        const dstype uq8 = uq[8];
        const dstype uq9 = uq[9];
        const dstype uq10 = uq[10];
        const dstype uq11 = uq[11];
        const dstype v0 = v[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = -0.01 + uq0;
        const dstype x1 = 0.5 + 0.318309886183791*Kokkos::atan(1000.0*x0);
        const dstype x2 = x0*x1;
        const dstype x3 = 0.000318309780080525 + x2;
        const dstype x4 = Kokkos::pow(x3, 2);
        const dstype x5 = 1 + 1000000.0*x4;
        const dstype x6 = Kokkos::pow(x5, -1);
        const dstype x7 = x1 + 318.309886183791*x0/(1 + 1000000.0*Kokkos::pow(x0, 2));
        const dstype x8 = 636.619772367581*x6*x7 - 636619772.367581*x4*x7/Kokkos::pow(x5, 2);
        const dstype x9 = v0*x8;
        const dstype x10 = Kokkos::pow(uq1, 2);
        const dstype x11 = 0.0103183097800805 + x2;
        const dstype x12 = Kokkos::pow(x11, -2);
        const dstype x13 = x12*x10;
        const dstype x14 = Kokkos::pow(x11, -1);
        const dstype x15 = uq2*x14;
        const dstype x16 = 0.5 + 318.309886183791*x3*x6 + 0.318309886183791*Kokkos::atan(1000.0*x3);
        const dstype x17 = uq8*x16;
        const dstype x18 = uq10 - x15*x17;
        const dstype x19 = x14*x18;
        const dstype x20 = uq1*x14;
        const dstype x21 = uq4*x16;
        const dstype x22 = uq5 - x20*x21;
        const dstype x23 = x22*x14;
        const dstype x24 = -x19 + 2*x23;
        const dstype x25 = Kokkos::pow(uq2, 2);
        const dstype x26 = x25*x12;
        const dstype x27 = x13 + x26;
        const dstype x28 = 0.5*x11;
        const dstype x29 = -1.0 + mu0;
        const dstype x30 = -0.001 + x29*(uq3 - x28*x27);
        const dstype x31 = 0.5 + 0.318309886183791*Kokkos::atan(1000.0*x30);
        const dstype x32 = x30*x31;
        const dstype x33 = 0.00131830978008052 + x32;
        const dstype x34 = x7*x12;
        const dstype x35 = x34*x33;
        const dstype x36 = 1.0*mu0;
        const dstype x37 = Kokkos::pow(mu3, 2)*mu9;
        const dstype x38 = x36*x37;
        const dstype x39 = Kokkos::pow(x11, -3);
        const dstype x40 = x7*x39;
        const dstype x41 = 2*x40;
        const dstype x42 = -x41*x10 - x41*x25;
        const dstype x43 = 0.5*x27;
        const dstype x44 = -x42*x28 - x7*x43;
        const dstype x45 = x31*x29;
        const dstype x46 = 318.309886183791*x30*x29/(1 + 1000000.0*Kokkos::pow(x30, 2));
        const dstype x47 = x44*x45 + x44*x46;
        const dstype x48 = x47*x14;
        const dstype x49 = x33*x14;
        const dstype x50 = 110.4 + x49*x38;
        const dstype x51 = Kokkos::pow(mu1, -1);
        const dstype x52 = 110.4 + mu9;
        const dstype x53 = Kokkos::pow(mu3, 6);
        const dstype x54 = x53*Kokkos::pow(mu0, 3);
        const dstype x55 = x54*Kokkos::pow(x33, 3);
        const dstype x56 = Kokkos::sqrt(x55*x39);
        const dstype x57 = x52*x51*x56;
        const dstype x58 = x57/Kokkos::pow(x50, 2);
        const dstype x59 = (-x35*x38 + x48*x38)*x58;
        const dstype x60 = 0.666666666666667*x59;
        const dstype x61 = x60*x24;
        const dstype x62 = Kokkos::pow(x33, 2);
        const dstype x63 = x62*x54;
        const dstype x64 = x63*x39;
        const dstype x65 = Kokkos::pow(x11, -4);
        const dstype x66 = Kokkos::pow(x50, -1);
        const dstype x67 = x66*x52*x51/x56;
        const dstype x68 = x67*(3*x64*x47 - 3*x7*x65*x55);
        const dstype x69 = 0.333333333333333*x68;
        const dstype x70 = x69*x24;
        const dstype x71 = x22*x12;
        const dstype x72 = x7*x71;
        const dstype x73 = uq1*x34;
        const dstype x74 = x8*uq4;
        const dstype x75 = x73*x21 - x74*x20;
        const dstype x76 = x75*x14;
        const dstype x77 = x12*x18;
        const dstype x78 = x7*x77;
        const dstype x79 = uq2*x34;
        const dstype x80 = x8*uq8;
        const dstype x81 = x79*x17 - x80*x15;
        const dstype x82 = x81*x14;
        const dstype x83 = x66*x57;
        const dstype x84 = 0.666666666666667*x83;
        const dstype x85 = (-2*x72 + 2*x76 + x78 - x82)*x84;
        const dstype x86 = uq6 - x21*x15;
        const dstype x87 = uq9 - x20*x17;
        const dstype x88 = x86*x14 + x87*x14;
        const dstype x89 = 1.0*x88*x59;
        const dstype x90 = x87*x12;
        const dstype x91 = x73*x17 - x80*x20;
        const dstype x92 = x86*x12;
        const dstype x93 = -x74*x15 + x79*x21;
        const dstype x94 = 1.0*x83;
        const dstype x95 = (-x7*x90 - x7*x92 + x91*x14 + x93*x14)*x94;
        const dstype x96 = 0.5*x68;
        const dstype x97 = x88*x96;
        const dstype x98 = -x89 + x95 + x97 - uq1*x79;
        const dstype x99 = x88*x94;
        const dstype x100 = Kokkos::pow(mu2, -1);
        const dstype x101 = x36*x100;
        const dstype x102 = x12*x101;
        const dstype x103 = x59*x102;
        const dstype x104 = Kokkos::pow(x29, -1);
        const dstype x105 = x33*x16;
        const dstype x106 = 0.000318309780080518 + x32;
        const dstype x107 = Kokkos::pow(x106, 2);
        const dstype x108 = 1 + 1000000.0*x107;
        const dstype x109 = Kokkos::pow(x108, -1);
        const dstype x110 = 0.5 + 318.309886183791*x109*x106 + 0.318309886183791*Kokkos::atan(1000.0*x106);
        const dstype x111 = uq1*x71 + uq2*x92;
        const dstype x112 = x43*x16;
        const dstype x113 = uq7 - uq4*x112 - x11*x111;
        const dstype x114 = x29*x11;
        const dstype x115 = x113*x114;
        const dstype x116 = -uq4*x105 + x110*x115;
        const dstype x117 = x104*x116;
        const dstype x118 = x83*x104;
        const dstype x119 = 2.0*x40*x118;
        const dstype x120 = mu0*x100;
        const dstype x121 = x116*x120;
        const dstype x122 = -x35 + x48 - uq3*x34;
        const dstype x123 = x96*x12*x104;
        const dstype x124 = x7*x29*x110;
        const dstype x125 = 0.5*x42;
        const dstype x126 = x8*x43;
        const dstype x127 = uq1*x41;
        const dstype x128 = uq1*x12;
        const dstype x129 = uq2*x41;
        const dstype x130 = uq2*x12;
        const dstype x131 = x110*x114;
        const dstype x132 = x8*x33;
        const dstype x133 = 636619772.367581*x107/Kokkos::pow(x108, 2);
        const dstype x134 = 636.619772367581*x109;
        const dstype x135 = -x47*x133 + x47*x134;
        const dstype x136 = x47*x16;
        const dstype x137 = x102*x118;
        const dstype x138 = 2*x19 - x23;
        const dstype x139 = x60*x138;
        const dstype x140 = (x72 - x76 - 2*x78 + 2*x82)*x84;
        const dstype x141 = x69*x138;
        const dstype x142 = uq1*x90 + uq2*x77;
        const dstype x143 = uq11 - uq8*x112 - x11*x142;
        const dstype x144 = -uq8*x105 + x131*x143;
        const dstype x145 = x104*x144;
        const dstype x146 = x114*x143;
        const dstype x147 = x120*x144;
        const dstype x148 = 1.0*x45;
        const dstype x149 = -x20*x148 - x46*x20;
        const dstype x150 = x37*mu0;
        const dstype x151 = 0.666666666666667*x150;
        const dstype x152 = x58*x14;
        const dstype x153 = x151*x152;
        const dstype x154 = x24*x153;
        const dstype x155 = x64*x67;
        const dstype x156 = 1.0*x155;
        const dstype x157 = x24*x156;
        const dstype x158 = 1.33333333333333*x83;
        const dstype x159 = x21*x12;
        const dstype x160 = x88*x38;
        const dstype x161 = x12*x17;
        const dstype x162 = 1.5*x155;
        const dstype x163 = x88*x162;
        const dstype x164 = x15 + x163*x149 - x94*x161 - x160*x149*x152;
        const dstype x165 = x83*x14;
        const dstype x166 = 0.666666666666667*x165;
        const dstype x167 = x24*x149;
        const dstype x168 = x58*x151;
        const dstype x169 = x128*x168;
        const dstype x170 = x63*x67*x65;
        const dstype x171 = uq1*x170;
        const dstype x172 = 1.0*x171;
        const dstype x173 = 1.0*x130;
        const dstype x174 = x88*x149;
        const dstype x175 = x58*x150;
        const dstype x176 = x174*x175;
        const dstype x177 = x39*x16;
        const dstype x178 = uq8*x177;
        const dstype x179 = uq2*x178;
        const dstype x180 = uq2*x170;
        const dstype x181 = 1.5*x180;
        const dstype x182 = x100*x117;
        const dstype x183 = 1.0*x58*x37*x39*Kokkos::pow(mu0, 2);
        const dstype x184 = x183*x149;
        const dstype x185 = uq4*x177;
        const dstype x186 = uq1*x185;
        const dstype x187 = 1.5*x62*x67*x53*Kokkos::pow(mu0, 4)/Kokkos::pow(x11, 5);
        const dstype x188 = x187*x182;
        const dstype x189 = -x133*x149 + x134*x149;
        const dstype x190 = 1.0*x128;
        const dstype x191 = x16*x149;
        const dstype x192 = x49 + uq3*x14;
        const dstype x193 = x138*x149;
        const dstype x194 = 1.0*x165;
        const dstype x195 = x88*x194;
        const dstype x196 = uq1*x178;
        const dstype x197 = x168*x130;
        const dstype x198 = 1.5*x171;
        const dstype x199 = uq2*x185;
        const dstype x200 = 1.0*x180;
        const dstype x201 = x100*x145;
        const dstype x202 = -x15*x148 - x46*x15;
        const dstype x203 = x88*x202;
        const dstype x204 = x20 + x203*x162 - x94*x159 - x38*x203*x152;
        const dstype x205 = x24*x202;
        const dstype x206 = x175*x173;
        const dstype x207 = x202*x182;
        const dstype x208 = -x202*x133 + x202*x134;
        const dstype x209 = x16*x202;
        const dstype x210 = x202*x138;
        const dstype x211 = x175*x190;
        const dstype x212 = x201*x202;
        const dstype x213 = x45 + x46;
        const dstype x214 = x14*x213;
        const dstype x215 = x58*x214;
        const dstype x216 = x215*x151;
        const dstype x217 = x213*x156;
        const dstype x218 = x213*x163 - x215*x160;
        const dstype x219 = x14 + x214;
        const dstype x220 = x24*x213;
        const dstype x221 = x88*x213;
        const dstype x222 = -x213*x133 + x213*x134;
        const dstype x223 = x16*x213;
        const dstype x224 = x213*x138;
        const dstype x225 = x213*x201;
        const dstype x226 = v0*x16;
        const dstype x227 = x128*x158;
        const dstype x228 = x83*x173;
        const dstype x229 = -x16*x228;
        const dstype x230 = x10*x177;
        const dstype x231 = x25*x177;
        const dstype x232 = x137*(-x105 + x131*(-x112 - (-x230 - x231)*x11));
        const dstype x233 = x84*x128;
        const dstype x234 = -0.333333333333333*uq2*uq1*x83*x177;
        const dstype x235 = v0 + 1.33333333333333*x165;
        const dstype x236 = x83*x190;
        const dstype x237 = x110*x120;
        const dstype x238 = -x237*x236;
        const dstype x239 = -x166;
        const dstype x240 = x84*x130;
        const dstype x241 = v0 + x194;
        const dstype x242 = -x237*x228;
        const dstype x243 = v0 + x101*x110*x165;
        const dstype x244 = -x16*x236;
        const dstype x245 = x130*x158;

        f[0] = x9*uq4;
        f[1] = x47 - x61 + x70 + x85 - x7*x13;
        f[2] = x98;
        f[3] = uq1*x122 - x103*x117 - x119*x121 + x123*x121 + x137*(-uq4*x132 - uq4*x136 + x113*x124 + x115*x135 + x131*(-uq4*x126 - x21*x125 - x7*x111 - (-x22*x127 + x75*x128 - x86*x129 + x93*x130)*x11)) - x61*x20 + x70*x20 - x79*x99 + x85*x20 - x89*x15 + x95*x15 + x97*x15 - x84*x73*x24;
        f[4] = x9*uq8;
        f[5] = x98;
        f[6] = -x139 + x140 + x141 + x47 - x7*x26;
        f[7] = uq2*x122 - x103*x145 - x119*x147 + x123*x147 + x137*(-uq8*x132 - uq8*x136 + x124*x143 + x131*(-uq8*x126 - x17*x125 - x7*x142 - (-x18*x129 + x81*x130 - x87*x127 + x91*x128)*x11) + x135*x146) - x15*x139 + x15*x140 + x15*x141 - x73*x99 - x89*x20 + x95*x20 + x97*x20 - x84*x79*x138;
        f[8] = 1;
        f[9] = x149 + 2*x20 - x149*x154 + x149*x157 - x158*x159;
        f[10] = x164;
        f[11] = x192 + x137*(-uq4*x191 + x115*x189 + x131*(-x11*(-x186 + x71) - x21*x190)) + x167*x172 - x169*x167 + x174*x181 - x176*x173 - x182*x184 - x186*x158 + x188*x149 + x20*x149 + x24*x166 - x94*x179;
        f[12] = 0;
        f[13] = x164;
        f[14] = x149 - x193*x153 + x193*x156 + x84*x159;
        f[15] = x195 + x137*(-uq8*x191 + x131*(-x11*(-x196 + x90) - x17*x190) + x189*x146) + x15*x149 + x174*x198 - x176*x190 - x197*x193 + x200*x193 - x201*x184 + x84*x199 - x94*x196 + x201*x187*x149;
        f[16] = 0;
        f[17] = x202 - x202*x154 + x202*x157 + x84*x161;
        f[18] = x204;
        f[19] = x195 + x137*(-uq4*x209 + x131*(-x11*(-x199 + x92) - x21*x173) + x208*x115) + x20*x202 + x203*x181 - x203*x206 - x205*x169 + x205*x172 - x207*x183 + x207*x187 + x84*x196 - x94*x199;
        f[20] = 1;
        f[21] = x204;
        f[22] = 2*x15 + x202 - x161*x158 - x210*x153 + x210*x156;
        f[23] = x192 + x137*(-uq8*x209 + x131*(-x11*(-x179 + x77) - x17*x173) + x208*x146) + x15*x202 + x166*x138 - x179*x158 + x203*x198 - x210*x197 + x210*x200 - x211*x203 - x212*x183 + x212*x187 - x94*x186;
        f[24] = 0;
        f[25] = x213 - x24*x216 + x24*x217;
        f[26] = x218;
        f[27] = uq1*x219 + x137*(-uq4*x223 + x222*x115) - x206*x221 + x213*x188 - x220*x169 + x220*x172 + x221*x181 - x213*x183*x182;
        f[28] = 0;
        f[29] = x218;
        f[30] = x213 - x216*x138 + x217*x138;
        f[31] = uq2*x219 + x137*(-uq8*x223 + x222*x146) + x200*x224 - x211*x221 + x221*x198 - x224*x197 - x225*x183 + x225*x187;
        f[32] = x226;
        f[33] = -x16*x227;
        f[34] = x229;
        f[35] = x232 - x230*x158 - x94*x231;
        f[36] = 0;
        f[37] = x229;
        f[38] = x16*x233;
        f[39] = x234;
        f[40] = 0;
        f[41] = x235;
        f[42] = 0;
        f[43] = x227 + x238;
        f[44] = 0;
        f[45] = 0;
        f[46] = x239;
        f[47] = -x240;
        f[48] = 0;
        f[49] = 0;
        f[50] = x241;
        f[51] = x228 + x242;
        f[52] = 0;
        f[53] = x194;
        f[54] = 0;
        f[55] = x236;
        f[56] = 0;
        f[57] = 0;
        f[58] = 0;
        f[59] = x243;
        f[60] = 0;
        f[61] = 0;
        f[62] = 0;
        f[63] = 0;
        f[64] = 0;
        f[65] = x16*x240;
        f[66] = x244;
        f[67] = x234;
        f[68] = x226;
        f[69] = x244;
        f[70] = -x16*x245;
        f[71] = x232 - x231*x158 - x94*x230;
        f[72] = 0;
        f[73] = 0;
        f[74] = x194;
        f[75] = x228;
        f[76] = 0;
        f[77] = x241;
        f[78] = 0;
        f[79] = x236 + x238;
        f[80] = 0;
        f[81] = x239;
        f[82] = 0;
        f[83] = -x233;
        f[84] = 0;
        f[85] = 0;
        f[86] = x235;
        f[87] = x242 + x245;
        f[88] = 0;
        f[89] = 0;
        f[90] = 0;
        f[91] = 0;
        f[92] = 0;
        f[93] = 0;
        f[94] = 0;
        f[95] = x243;
    }

    KOKKOS_INLINE_FUNCTION static
    void source_jac_uq(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 0;
        f[1] = 0;
        f[2] = 0;
        f[3] = 0;
        f[4] = 0;
        f[5] = 0;
        f[6] = 0;
        f[7] = 0;
        f[8] = 0;
        f[9] = 0;
        f[10] = 0;
        f[11] = 0;
        f[12] = 0;
        f[13] = 0;
        f[14] = 0;
        f[15] = 0;
        f[16] = 0;
        f[17] = 0;
        f[18] = 0;
        f[19] = 0;
        f[20] = 0;
        f[21] = 0;
        f[22] = 0;
        f[23] = 0;
        f[24] = 0;
        f[25] = 0;
        f[26] = 0;
        f[27] = 0;
        f[28] = 0;
        f[29] = 0;
        f[30] = 0;
        f[31] = 0;
        f[32] = 0;
        f[33] = 0;
        f[34] = 0;
        f[35] = 0;
        f[36] = 0;
        f[37] = 0;
        f[38] = 0;
        f[39] = 0;
        f[40] = 0;
        f[41] = 0;
        f[42] = 0;
        f[43] = 0;
        f[44] = 0;
        f[45] = 0;
        f[46] = 0;
        f[47] = 0;
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 2) {

            f[0] = 1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 1;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 3) {

            f[0] = 1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
        else if (ib == 2) {

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
        else if (ib == 3) {
            const dstype mu8 = mu[8];
            const dstype mu9 = mu[9];
            const dstype mu10 = mu[10];

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = mu8*mu10/mu9;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fint(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq3 = uq[3];
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype uq6 = uq[6];
        const dstype uq7 = uq[7];
        const dstype uq8 = uq[8];
        const dstype uq9 = uq[9];
        const dstype uq10 = uq[10];
        const dstype uq11 = uq[11];
        const dstype uhat0 = uh[0];
        const dstype uhat1 = uh[1];
        const dstype uhat2 = uh[2];
        const dstype uhat3 = uh[3];
        const dstype n0 = n[0];
        const dstype n1 = n[1];
        const dstype tau0 = tau[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = Kokkos::pow(uhat0, -2);
        const dstype x1 = 0.5*(x0*Kokkos::pow(uhat1, 2) + x0*Kokkos::pow(uhat2, 2));
        const dstype x2 = uhat3 - x1*uhat0;
        const dstype x3 = -1.0 + mu0;
        const dstype x4 = x2*x3;
        const dstype x5 = Kokkos::pow(uhat0, -1);
        const dstype x6 = x5*uq8;
        const dstype x7 = x0*uhat2;
        const dstype x8 = x0*uhat1;
        const dstype x9 = x3*uhat0;
        const dstype x10 = 1.0*mu0;
        const dstype x11 = x0*x10*(110.4 + mu9)*Kokkos::sqrt(Kokkos::pow(x2, 3)*Kokkos::pow(x3, 3)*Kokkos::pow(mu3, 6)*Kokkos::pow(mu0, 3)/Kokkos::pow(uhat0, 3))/(x3*mu2*mu1*(110.4 + x4*x5*x10*Kokkos::pow(mu3, 2)*mu9));
        const dstype x12 = x5*uq4;

        f[0] = tau0*(-uhat3 + uq3) + n0*x11*(-x4*uq4 + x9*(uq7 - x1*uq4 - (x7*(uq6 - x12*uhat2) + x8*(uq5 - x12*uhat1))*uhat0)) + n1*x11*(-x4*uq8 + x9*(uq11 - uhat0*(x7*(uq10 - x6*uhat2) + x8*(uq9 - x6*uhat1)) - x1*uq8));
    }

    KOKKOS_INLINE_FUNCTION static
    void fint_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uhat0 = uh[0];
        const dstype uhat1 = uh[1];
        const dstype uhat2 = uh[2];
        const dstype uhat3 = uh[3];
        const dstype n0 = n[0];
        const dstype n1 = n[1];
        const dstype tau0 = tau[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = Kokkos::pow(uhat0, -2);
        const dstype x1 = 1.0*mu0;
        const dstype x2 = Kokkos::pow(uhat2, 2);
        const dstype x3 = x0*x2;
        const dstype x4 = Kokkos::pow(uhat1, 2);
        const dstype x5 = x0*x4;
        const dstype x6 = uhat3 - 0.5*(x3 + x5)*uhat0;
        const dstype x7 = -1.0 + mu0;
        const dstype x8 = x6*x7;
        const dstype x9 = x1/uhat0;
        const dstype x10 = Kokkos::pow(uhat0, -3);
        const dstype x11 = (110.4 + mu9)*Kokkos::sqrt(Kokkos::pow(x6, 3)*Kokkos::pow(x7, 3)*x10*Kokkos::pow(mu3, 6)*Kokkos::pow(mu0, 3))/(mu2*mu1*(110.4 + x8*x9*Kokkos::pow(mu3, 2)*mu9));
        const dstype x12 = x0*x1*x11;
        const dstype x13 = n0*x12;
        const dstype x14 = (-x8 + x7*uhat0*(-0.5*x3 - 0.5*x5 - (-x2*x10 - x4*x10)*uhat0))/x7;
        const dstype x15 = x9*x11;
        const dstype x16 = n1*x12;

        f[0] = 0;
        f[1] = 0;
        f[2] = 0;
        f[3] = tau0;
        f[4] = x14*x13;
        f[5] = -x13*uhat1;
        f[6] = -x13*uhat2;
        f[7] = n0*x15;
        f[8] = x14*x16;
        f[9] = -x16*uhat1;
        f[10] = -x16*uhat2;
        f[11] = n1*x15;
    }

    KOKKOS_INLINE_FUNCTION static
    void fint_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq4 = uq[4];
        const dstype uq5 = uq[5];
        const dstype uq6 = uq[6];
        const dstype uq7 = uq[7];
        const dstype uq8 = uq[8];
        const dstype uq9 = uq[9];
        const dstype uq10 = uq[10];
        const dstype uq11 = uq[11];
        const dstype uhat0 = uh[0];
        const dstype uhat1 = uh[1];
        const dstype uhat2 = uh[2];
        const dstype uhat3 = uh[3];
        const dstype n0 = n[0];
        const dstype n1 = n[1];
        const dstype tau0 = tau[0];
        const dstype mu0 = mu[0];
        const dstype mu1 = mu[1];
        const dstype mu2 = mu[2];
        const dstype mu3 = mu[3];
        const dstype mu9 = mu[9];

        const dstype x0 = -1.0 + mu0;
        const dstype x1 = Kokkos::pow(uhat0, -2);
        const dstype x2 = Kokkos::pow(uhat2, 2);
        const dstype x3 = x2*x1;
        const dstype x4 = Kokkos::pow(uhat1, 2);
        const dstype x5 = x1*x4;
        const dstype x6 = x3 + x5;
        const dstype x7 = 0.5*uhat0;
        const dstype x8 = uhat3 - x6*x7;
        const dstype x9 = x0*x8;
        const dstype x10 = x9*mu0;
        const dstype x11 = Kokkos::pow(uhat0, -1);
        const dstype x12 = Kokkos::pow(mu3, 2);
        const dstype x13 = 1.0*x12*mu9;
        const dstype x14 = x13*x11;
        const dstype x15 = 110.4 + x14*x10;
        const dstype x16 = Kokkos::pow(x15, -1);
        const dstype x17 = x16*mu0;
        const dstype x18 = Kokkos::pow(mu2, -1);
        const dstype x19 = Kokkos::pow(mu1, -1);
        const dstype x20 = 110.4 + mu9;
        const dstype x21 = Kokkos::pow(uhat0, -3);
        const dstype x22 = Kokkos::pow(mu3, 6);
        const dstype x23 = Kokkos::pow(mu0, 3);
        const dstype x24 = Kokkos::pow(x0, 3);
        const dstype x25 = Kokkos::pow(x8, 3)*x24*x22*x23;
        const dstype x26 = Kokkos::sqrt(x25*x21);
        const dstype x27 = x20*x26*x19*x18;
        const dstype x28 = n0*x27;
        const dstype x29 = x28*x17;
        const dstype x30 = Kokkos::pow(x0, -1);
        const dstype x31 = uq4*uhat2;
        const dstype x32 = x31*x11;
        const dstype x33 = uq6 - x32;
        const dstype x34 = x1*x33;
        const dstype x35 = x34*uhat2;
        const dstype x36 = uq4*uhat1;
        const dstype x37 = x36*x11;
        const dstype x38 = uq5 - x37;
        const dstype x39 = x1*x38;
        const dstype x40 = x39*uhat1;
        const dstype x41 = 0.5*uq4;
        const dstype x42 = x0*(uq7 - x6*x41 - (x35 + x40)*uhat0);
        const dstype x43 = x42*uhat0 - x9*uq4;
        const dstype x44 = x43*x30;
        const dstype x45 = 2.0*x21;
        const dstype x46 = 1.0*x1;
        const dstype x47 = 2*x21;
        const dstype x48 = -x2*x47 - x4*x47;
        const dstype x49 = -0.5*x3 - 0.5*x5 - x7*x48;
        const dstype x50 = x0*x49;
        const dstype x51 = x46*mu0*(x50*x14*mu0 - x46*x12*x10*mu9);
        const dstype x52 = Kokkos::pow(x15, -2);
        const dstype x53 = x52*x28;
        const dstype x54 = x47*uhat1;
        const dstype x55 = Kokkos::pow(uhat0, -4);
        const dstype x56 = x4*x55;
        const dstype x57 = x47*uhat2;
        const dstype x58 = x2*x55;
        const dstype x59 = x0*uhat0;
        const dstype x60 = x46*x29;
        const dstype x61 = x60*x30;
        const dstype x62 = x20*x19*x18/x26;
        const dstype x63 = n0*x62;
        const dstype x64 = Kokkos::pow(x8, 2)*x22;
        const dstype x65 = 0.5*x1*(-3*x55*x25 + 3*x64*x49*x24*x23*x21);
        const dstype x66 = uq8*x11;
        const dstype x67 = x66*uhat2;
        const dstype x68 = uq10 - x67;
        const dstype x69 = x1*x68;
        const dstype x70 = x69*uhat2;
        const dstype x71 = x66*uhat1;
        const dstype x72 = uq9 - x71;
        const dstype x73 = x1*x72;
        const dstype x74 = x73*uhat1;
        const dstype x75 = 0.5*uq8;
        const dstype x76 = x0*(uq11 - x6*x75 - (x70 + x74)*uhat0);
        const dstype x77 = x76*uhat0 - x9*uq8;
        const dstype x78 = n1*x17;
        const dstype x79 = x78*x27;
        const dstype x80 = x79*x30;
        const dstype x81 = x77*x30;
        const dstype x82 = n1*x52*x27;
        const dstype x83 = x80*x46;
        const dstype x84 = x53*x43;
        const dstype x85 = x13*Kokkos::pow(mu0, 2);
        const dstype x86 = x85*x55;
        const dstype x87 = x86*uhat1;
        const dstype x88 = 1.0*x0;
        const dstype x89 = x63*x43;
        const dstype x90 = 1.5*Kokkos::pow(x0, 2)*x64*x16*Kokkos::pow(mu0, 4);
        const dstype x91 = x90/Kokkos::pow(uhat0, 6);
        const dstype x92 = x91*uhat1;
        const dstype x93 = x82*x77;
        const dstype x94 = n1*x77*x62;
        const dstype x95 = uq8*x46;
        const dstype x96 = uq8*x21;
        const dstype x97 = x86*uhat2;
        const dstype x98 = x91*uhat2;
        const dstype x99 = x85*x21;
        const dstype x100 = x90/Kokkos::pow(uhat0, 5);

        f[0] = x61*(x42 - uq4*x50 + x59*(-x35 - x40 - x41*x48 - (uq4*x56 + uq4*x58 - x54*x38 - x57*x33)*uhat0)) + x83*(x76 - uq8*x50 + x59*(-x70 - x74 - x75*x48 - (uq8*x56 + uq8*x58 - x68*x57 - x72*x54)*uhat0)) - x44*x45*x29 - x53*x51*x44 - x80*x77*x45 - x81*x82*x51 + x63*x65*x44*x17 + x81*x78*x62*x65;
        f[1] = x61*(x59*(-uhat0*(x39 - x36*x21) - x46*x36) + x88*x37) + x83*(x59*(-uhat0*(x73 - x96*uhat1) - x95*uhat1) + x88*x71) + x84*x87 + x87*x93 - x89*x92 - x92*x94;
        f[2] = x61*(x59*(-uhat0*(x34 - x31*x21) - x46*x31) + x88*x32) + x83*(x59*(-uhat0*(x69 - x96*uhat2) - x95*uhat2) + x88*x67) + x84*x97 - x89*x98 + x93*x97 - x98*x94;
        f[3] = -tau0 - uq4*x60 - x79*x95 - x84*x99 + x89*x100 - x93*x99 + x94*x100;
    }

    KOKKOS_INLINE_FUNCTION static
    void fext(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype uext[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq0 = uq[0];
        const dstype uhat0 = uh[0];
        const dstype uhat1 = uh[1];
        const dstype uhat2 = uh[2];
        const dstype uhat3 = uh[3];
        const dstype uext0 = uext[0];

        f[0] = -uhat0 + uq0;
        f[1] = -uhat1;
        f[2] = -uhat2;
        f[3] = -uhat3 + uhat0*uext0;
    }

    KOKKOS_INLINE_FUNCTION static
    void fext_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype uext[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 1;
        f[1] = 0;
        f[2] = 0;
        f[3] = 0;
        f[4] = 0;
        f[5] = 0;
        f[6] = 0;
        f[7] = 0;
        f[8] = 0;
        f[9] = 0;
        f[10] = 0;
        f[11] = 0;
        f[12] = 0;
        f[13] = 0;
        f[14] = 0;
        f[15] = 0;
        f[16] = 0;
        f[17] = 0;
        f[18] = 0;
        f[19] = 0;
        f[20] = 0;
        f[21] = 0;
        f[22] = 0;
        f[23] = 0;
        f[24] = 0;
        f[25] = 0;
        f[26] = 0;
        f[27] = 0;
        f[28] = 0;
        f[29] = 0;
        f[30] = 0;
        f[31] = 0;
        f[32] = 0;
        f[33] = 0;
        f[34] = 0;
        f[35] = 0;
        f[36] = 0;
        f[37] = 0;
        f[38] = 0;
        f[39] = 0;
        f[40] = 0;
        f[41] = 0;
        f[42] = 0;
        f[43] = 0;
        f[44] = 0;
        f[45] = 0;
        f[46] = 0;
        f[47] = 0;
    }

    KOKKOS_INLINE_FUNCTION static
    void fext_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype uext[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uext0 = uext[0];

        f[0] = -1;
        f[1] = 0;
        f[2] = 0;
        f[3] = uext0;
        f[4] = 0;
        f[5] = -1;
        f[6] = 0;
        f[7] = 0;
        f[8] = 0;
        f[9] = 0;
        f[10] = -1;
        f[11] = 0;
        f[12] = 0;
        f[13] = 0;
        f[14] = 0;
        f[15] = -1;
    }

};
